GET http://localhost:3001/api/v1/users/1

###

GET http://localhost:3001/api/v1/users

###

POST http://localhost:3001/api/v1/users
Content-Type: application/json

{
  "username": "admin",
  "password": "root123",
  "role": "admin"
}

###

POST http://localhost:3001/api/v1/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "root123"
}

### POSTS

GET http://localhost:3001/api/v1/posts

### 

POST http://localhost:3001/api/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTY3MjE4MTQ5MCwiZXhwIjoxNjcyMTgyMDkwfQ.gKLib6kYdynS66z7IE4ZGMIJ48pFrChC5ZyJIyISid4
Content-Type: application/json

{
  "title": "test test",
  "description": "test test"
}

###

GET http://localhost:3001/api/v1/posts/date
Content-Type: application/json

{
  "entryDates": [{"year": 2022, "date": 23}]
}

### EXPORTS

GET http://localhost:3001/api/v1/exports
Content-Type: application/json

{
  "entryDates": [{"year": 2022, "date": 23}]
}

###

GET http://localhost:3001/api/v1/exports/filter-user
Content-Type: application/json

{
  "entryArray": [1, 2],
  "columns": ["title", "description", "createdAt"]
}
